### ISSUE TITLE
Are those xml parsed from xxx.dcp files?

### ISSUE THREAD

**Issue by ProNoobLi** [abpy/FujifilmCameraProfiles#12]
Hi, Abpy, this is a great project.
I have a question about the source .dcp which are parsed into the xml files.
It's possible to parse the normal dcp files like "Fujifilm X100V Adobe Standard.dcp" into a readable xml, since I have access to the CameraProfiles in the LR folder. However, some fancy filters like "Classic Neg" "Classic Chrome" dcp files are hidden in the folder, how did you parse all these xmls?

Thanks

**Comment by abpy** [comment]
All of the fujifilm camera profiles are embedded and cannot be accessed.

Some, like Classic Neg can be found here:
`.../CameraRaw/Settings/Adobe/Profiles/Camera/Fujifilm/Fujifilm X100V/Fujifilm X100V Camera CLASSIC Neg.xmp`
but it relies on Provia as a base profile and wouldn't be usable on its own.

**Comment by ProNoobLi** [comment]
Thanks for your kind reply. But I still don't get the point:
1. "Fujifilm X100V Camera CLASSIC Neg.xmp" provides some tags instead of specific params, so how did you parse the CLASSIC Neg Cube?
2. My folder "C:\ProgramData\Adobe\CameraRaw\CameraProfiles" didn't contain any fancy dcps, like PROVIA, CLASSIC CHROME.... but you do have. How did you find them?
3. Can I make the statement that, the Classic Neg could be achieved by replacing the ColorTable from PROVIA by your provided cube?

**Comment by abpy** [comment]
Ok, I see what you mean. dcp's for provia, etc do not exist.
My profiles are made using images exported from camera raw. By comparing a linear image to a film one I can build a profile that approximates the original profile, but will work for any camera.

I'm not actually using CLASSIC Neg.xmp. I don't think replacing the table would work.

I am curious, do you have a fujifilm camera? Is there a particular profile you want to use with it?

**Comment by ProNoobLi** [comment]
Get! Thanks

I do have a Sony A7C, and one Fuji X100V borrowed from my friend. I love the Classic Neg look a lot and trying to hack out the dcp which could be applied on my Sony. What I plan to do is as:
1. Combine the camera-specific params in A7C_adobe_standard.dcp, like the UniqueName, Forward matrix... with the film parameters like ColorTable HSVShiftTable in the FujiClassicNeg.dcp. 
2. Then use it.

"By comparing a linear image to a film one I can build a profile that approximates the original profile, but will work for any camera." might be the way I need to do

**Comment by abpy** [comment]
So what you need is a [linear camera profile](https://abpy.github.io/2023/05/20/linear-profiles.html). It can be used as base for the .cube file in acr/lightroom.

I will add instructions to the readme on how to set this up.

There is no "FujiClassicNeg.dcp" because this look can not be achieved with just a HueSat LookTable. It has to be a 3d lut.

The "comparing" is a lot of code for data processing and interpolation.
