### ISSUE TITLE
SUPER COOL!

### ISSUE THREAD

**Issue by maxrpunkt** [abpy/FujifilmCameraProfiles#14]
Many thanks for creating this! Its super helpful! 

1) Do I understand it correctly, that you use Adobe Standard as "calibration standard".

2) Is there qualitatively a difference in generating a new profile from the cube LUTs or the XMLs? For one example image, I don't see a difference.

3) The file Sony ILCE-7CM2 Adobe Standard.xml does not have a ToneCurve section, but it seems to be not a problem.

4) The dcpTool reports "Information: ReductionMatrix1 has zero dimensions" when generating the dcp file, but this also seems to be not a problem.

5) I tried using a camera specific dcp file (Sony ILCE-7CM2 Camera ST.dcp) instead of ILCE-7CM2 Adobe Standard.dcp. This resulted in wrong colors. The files differ by values in the ForwardMatrix sections. Why does it only work well with the Adobe Standard file?

6) Have you compared the original Fuji JPG output to the output of your method using a different camera brand? At the first glance, the colors look great and qualitatively as expected, but I have not attempted a 1:1 comparison yet.

Cheers Max

**Comment by abpy** [comment]
I'm glad you like the profiles
1. They are designed to work with Adobe Standard.
2. The lut and dcp should look the same, but adobe does some adjustments like point curves after the look table and before the 3d lut. If you use these adjustments it will look different.
3. Actually all Adobe Standard dcp profiles have no curve. The default "adobe standard curve" is used if one is not included.
4. I'm not sure why it prints that. I've never seen a ReductionMatrix.
5. Camera Standard profiles are designed differently than a calibration profile, so they wont work if edited.
6. I haven't done a lot of comparison to jpegs but they are pretty similar. Different brands probably will have slightly different looks.

**Comment by maxrpunkt** [comment]
Many thanks for the explanations.
2. Does this mean: when additional modifications such as point curve adjustments are needed, use the dcp variant if possible?

**Comment by abpy** [comment]
Its really just a matter of preference
