### ISSUE TITLE
Are the regular + tone curve luts meant to be layered? 

### ISSUE THREAD

**Issue by abnormally-distributed** [abpy/FujifilmCameraProfiles#4]
I was wondering if the luts for a given profile are meant to be layered. Ie, applying Velvia, then Velvia tone curve. I'm going to guess the answer is no, since doing so crushes the shadows and blows the highlights. However that leaves me wondering why there are separate luts for the tone curves. I initially assumed that the ones with only the title of the film emulation are hue+chroma only, with the brightness separated into the tone curve file. Would you be able to clarify  the intended use?

**Comment by abpy** [comment]
You are pretty much correct. The <name>.cube is a 3d LUT and is the entire look. The <name>tone curve.cube is a 1d LUT.
The csv file is a hue-saturation-value table, and is meant to be used in adobe raw/lightroom together with the tone curve in a preset/profile.
