### ISSUE TITLE
Question regarding creation of dcp profile and the methods you used to generate the Look Table inside for the film simulation

### ISSUE THREAD

**Issue by tattwah** [abpy/FujifilmCameraProfiles#8]
First of all thank you for making (reverse engineering) the fujifilm profile. it has been very useful for those who wish to use it in other cameras/ other raw editors. However I have some questions that i do not understand and hopefully can get some guidance.

I know that for dcp files for use in LR the Colour Matrix, forward matrix and Reduction Matrix are CMOS dependant (camera specific).  However I am not sure about the Look table values inside the dcp profiles. When using your profile does the lookup table values need to be edited in relative to HueSatMap values in the dcp  as per camera model or we just only need to copy the Look Table and Tone Curve according to the film simulation? 

From my understanding the HSVmapping from the dcp will affect the final look generated by the Look Table  as well. Is this the case here?

My second question is regarding the method you used for the generation of the Look Table in the dcp. 

Do you mind sharing or making a tutorial on how to convert the target colour values via a colour checker (as in Jpeg film simulation color) into the format inside the dcp: (Example:  

 LookTable hueDivisions="36" satDivisions="16" valDivisions="12"
    Element HueDiv="0" SatDiv="0" ValDiv="0" HueShift="0.0" SatScale="1.0" ValScale="1.0"/
    Element HueDiv="0" SatDiv="0" ValDiv="1" HueShift="0.0" SatScale="1.0" ValScale="1.0"/
    Element HueDiv="0" SatDiv="0" ValDiv="2" HueShift="0.0" SatScale="1.0" ValScale="1.0"/

Any guide or info is much appreciated. 

P.S: Is there any way i can contact you on discord so that we can discuss more in person? thanks.

**Comment by abpy** [comment]
for dcp profiles:
The HueSatDeltas are part of the camera calibration and should be left unchanged.
The LookTable and ToneCurve are interchangeable.

As for how the tables and curves are made, it depends on what you're trying to do. I used python to process and output all the data and relied on scipy RBFInterpolator to interpolate the values.

**Comment by tattwah** [comment]
By LookTable and ToneCurve are interchangeable that means the same looktable and Tone curve will work with potentially any camera with a dcp correct?

Thanks for your heads up regarding the how the curve are made.

**Comment by abpy** [comment]
Sorry I should have elaborated on that. Yes, the same table works with profiles for different cameras. The calibration is unchanged and the film look is just added on top.

There are exceptions though. Adobe camera matching profiles (eg. 'camera standard') use the lookTable for both calibration and the look all in one table. So it can not be separated or changed without loosing the camera specific information.

Thanks for showing interest in the profiles. I may edit the readme to clarify things.

**Comment by tattwah** [comment]
That's right, I noticed when i try to move the look table and curve from the dcp of a camera profile to another camera profile (trying to obtain the JPEG look of other camera), The pictures that comes out slightly off in comparison to the actual one. When comparing test shots.
